python3: can't open file 'main.py': [Errno 2] No such file or directory
python3: can't open file 'main.py': [Errno 2] No such file or directory
python3: can't open file 'main.py': [Errno 2] No such file or directory
python3: can't open file 'main.py': [Errno 2] No such file or directory
python3: can't open file 'main.py': [Errno 2] No such file or directory
python3: can't open file 'main.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 27, in <module>
    f = open("pidport.conf", 'w')
PermissionError: [Errno 13] Permission denied: 'pidport.conf'
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/var/www/StableBuild/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 36, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
