Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 7, in <module>
    import processRequest
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 15
    print("Test: "sqlQuery)
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 7, in <module>
    import processRequest
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 15
    print("Test: " sqlQuery)
                          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 7, in <module>
    import processRequest
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 15
    print("Test: " sqlQuery)
                          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 60, in <module>
    completedRequest = processRequest.ProcessRequest(data)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 13, in ProcessRequest
    sqlQuery = sqlParmsToQuery.sqlParmsToQuery(sqlParms)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/sqlParmsToQuery.py", line 7, in sqlParmsToQuery
    query = "SELECT * FROM pet WHERE " + completedRequest
NameError: name 'completedRequest' is not defined
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 60, in <module>
    completedRequest = processRequest.ProcessRequest(data)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 13, in ProcessRequest
    sqlQuery = sqlParmsToQuery.sqlParmsToQuery(sqlParms)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/sqlParmsToQuery.py", line 7, in sqlParmsToQuery
    query = "SELECT * FROM pet WHERE " + completedRequest
NameError: name 'completedRequest' is not defined
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 60, in <module>
    completedRequest = processRequest.ProcessRequest(data)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 13, in ProcessRequest
    sqlQuery = sqlParmsToQuery.sqlParmsToQuery(sqlParms)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/sqlParmsToQuery.py", line 7, in sqlParmsToQuery
    query = "SELECT * FROM pet WHERE " + completedRequest
NameError: name 'completedRequest' is not defined
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 60, in <module>
    completedRequest = processRequest.ProcessRequest(data)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 13, in ProcessRequest
    sqlQuery = sqlParmsToQuery.sqlParmsToQuery(sqlParms)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/sqlParmsToQuery.py", line 7, in sqlParmsToQuery
    query = "SELECT * FROM pet WHERE " + completedRequest
NameError: name 'completedRequest' is not defined
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 60, in <module>
    completedRequest = processRequest.ProcessRequest(data)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/processRequest.py", line 13, in ProcessRequest
    sqlQuery = sqlParmsToQuery.sqlParmsToQuery(sqlParms)
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/sqlParmsToQuery.py", line 7, in sqlParmsToQuery
    query = "SELECT * FROM pet WHERE " + completedRequest
NameError: name 'completedRequest' is not defined
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 66, in <module>
    sql_data = sql_utils.get_dict(query)
NameError: name 'sql_utils' is not defined
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/colehoffele/Documents/CIS4250/ClinicalAnalysis/ClinicalAnalysisEngine/main/main.py", line 41, in <module>
    s.bind((host, port))
OSError: [Errno 98] Address already in use
